# Generated by Django 2.2.1 on 2019-08-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repertoire',
            old_name='first_name',
            new_name='nom_repertoire',
        ),
    ]
