# Generated by Django 2.2.1 on 2019-08-06 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0004_auto_20190806_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Repertoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=14)),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Repertoire')),
            ],
        ),
    ]
