# Generated by Django 2.2.1 on 2019-08-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='numero',
        ),
    ]
