# Generated by Django 2.2.1 on 2019-08-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_auto_20190806_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='repertoire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
