# Generated by Django 2.2.1 on 2019-08-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_auto_20190807_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoires', to=settings.AUTH_USER_MODEL),
        ),
    ]
